### ISSUE TITLE
Type definitions for typescript

### ISSUE THREAD

**Issue by AlinaDogariu** [TrueCar/react-launch-darkly#110]
There are no type definitions for typescript for this project that I could find. Would it be ok to add some? 

If you're ok with it, I can start working on it

**Comment by maxhilliard** [comment]
I'm also keen to contribute to this if it goes ahead ☝️

**Comment by sethbattin** [comment]
Absolutely, please do.  If you're feeling ambitious, convert 100% to typescript and write flow definitions instead :yolo:

Truecar's main react project is currently in incremental adoption of typescript into our otherwise flowjs-heavy code.  So we can certainly help test the patch whenever it is ready.  Other packages' typescript definitions pass linting and other CI steps, so I'm optimistic. :)

That still might lead to asking for changes for compatibility though, and I'm afraid I can't accurately list those requirements ahead of time (sorry, just not my expertise).  However, if it's some problem unique to our codebase, we simply won't update to the newer version until we get our js typing better sorted out.  

Definitely submit a PR so we can see how it goes!
