### ISSUE TITLE
react-broadcast dependency means this repo will not be compatible with React 16

### ISSUE THREAD

**Issue by jasonbarry** [TrueCar/react-launch-darkly#32]
[react-broadcast](https://github.com/ReactTraining/react-broadcast) still uses PropTypes, which was deprecated in React 15.5 and will be removed in React 16 (which just [came into beta](https://github.com/facebook/react/issues/10294)).

I'd file a bug on the react-broadcast repo, but they don't accept issues, which is equally alarming. 

I'd suggest removing the react-broadcast dependency from this project.

**Comment by threehams** [comment]
React.PropTypes is deprecated and will be removed in favor of the prop-types library. react-broadcast was updated to use the new dependency months ago:
https://github.com/ReactTraining/react-broadcast/pull/31

The decision to disable issues isn't one I agree with, but it's not alarming or uncommon.

react-broadcast provides a generalized way of broadcasting context updates rather than having them stopped by shouldComponentUpdate short-circuiting; there's very little value to writing that ourselves.

**Comment by jasonbarry** [comment]
Dropping in React 16 into my project points to an error from react-broadcast: 

<img width="469" alt="screen shot 2017-09-27 at 12 23 59 am" src="https://user-images.githubusercontent.com/236451/30900875-743a526c-a31a-11e7-89e0-a2d0f0143cdb.png">

**Comment by jacobmoretti** [comment]
Looks like we need to update react-broadcast, we're on an older version in this project.

**Comment by jacobmoretti** [comment]
Hoping to resolve this with: https://github.com/TrueCar/react-launch-darkly/pull/42

**Comment by jacobmoretti** [comment]
@jasonbarry Just pushed out a new release to npm: https://github.com/TrueCar/react-launch-darkly/releases/tag/v1.0.0 Can you see if this fixes your issue?

**Comment by jasonbarry** [comment]
@jacobmoretti I'll give this a try tonight! Thanks

**Comment by jasonbarry** [comment]
@jacobmoretti it works! Thanks so much 🎉
