### ISSUE TITLE
Default export is deprecated - causes warning

### ISSUE THREAD

**Issue by Kamahl19** [TrueCar/react-launch-darkly#89]
`[LaunchDarkly] "default export" is deprecated, please use "named LDClient export"`

**Comment by jamesmosier** [comment]
The fix for this is to change [this line](https://github.com/TrueCar/react-launch-darkly/blob/master/src/lib/utils.js#L1) to `import * as launchDarklyBrowser from "ldclient-js";`. Once that is done the tests will need fixed (I believe the mocks get messed up is the reason why).

Also just for reference, [the LaunchDarkly team said](https://github.com/launchdarkly/js-client/issues/111) in future `ldclient-js` versions that they'll be removing the default export. I'm sure it'll be a little while and would certainly be a major version bump.

**Comment by janhartmann** [comment]
Any updates on this?

**Comment by jamesmosier** [comment]
@janhartmann I haven't had time to work on it, so it is up for grabs as far as I know!

**Comment by jacobmoretti** [comment]
Fixed as part of https://github.com/TrueCar/react-launch-darkly/pull/91. Release patch version coming up!

**Comment by jacobmoretti** [comment]
Released as part of 3.1.1: https://github.com/TrueCar/react-launch-darkly/releases/tag/v3.1.1
